USE canine_blood;

CREATE TABLE IF NOT EXISTS vet_clinics (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  clinic_name VARCHAR(100) NOT NULL,
  clinic_contact_details VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  hashed_password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_vet_clinics_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;